name: macOS Build and Test

on:
  push:
    branches: [ "eoleun" ]
  pull_request:
    branches: [ "eoleun" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Select Xcode 15.4
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app/Contents/Developer

    - name: Build macOS App
      run: xcodebuild -project DateReminder.xcodeproj -scheme DateReminder -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Run Unit Tests
      run: xcodebuild test -project DateReminder.xcodeproj -scheme DateReminder -configuration Debug -destination 'platform=macOS'

    - name: Package App into .dmg
      run: |
        mkdir -p output
        hdiutil create -volname "DateReminder" -srcfolder build/Release/DateReminder.app -ov -format UDZO output/DateReminder.dmg

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DateReminder
        path: output/DateReminder.dmg
